version: "3"

services:
  db:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpw
      MYSQL_USER: user
      MYSQL_PASSWORD: mysqlpw
      MYSQL_DATABASE: vacations_schema
    volumes:
      - ./new.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    security_opt:
      - seccomp:unconfined

  node-server:
    build:
      context: ./project3-server
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3200:3200"

  ui:
    build:
      context: ./project3-client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
